### ISSUE TITLE
support centos 7.7 8.0

### ISSUE THREAD

**Issue by peterwillcn** [slzcc/crane#2]
support centos 7.7 8.0

**Comment by slzcc** [comment]
抱歉，没看到 issus。
crane 是支持 centos 7 的，但我没有尝试 7.7 版本过，不知道有啥问题。
centos 8 暂不支持，我也没有使用过，如果想支持请在 role 目录下找到类似的配置 ansible_distribution_major_version == "7" 改为 8 进行尝试。

**Comment by slzcc** [comment]
在 v1.16.2.3 中已经加入了对 centos 8 的支持，可以尝试，感谢支持。
